
# The docker-compose.yml file describes the services that make your app. In this example those services are a web server and database.

version: "3.3"
   
services:
    django:
        build: .
        container_name: django
        command: python manage.py runserver 0.0.0.0:8000
        volumes:
            - .:/home/app/webapp
        ports:
            - "8000:8000"
        depends_on:
            - pgdb
    pgdb:
        image: postgres:12
        container_name: pgdb
        environment:
        - POSTGRES_DB=postgres
        - POSTGRES_USER=postgres
        - POSTGRES_PASSWORD=postgres